
# Environment 
NUM_SERVERS = 3
MAX_ESTIMATED_WORKLOAD = 50
SERVER_MAX_WORKLOAD = 5 * MAX_ESTIMATED_WORKLOAD
PROCESS_SPEED = 5


# Distribution of Estimated Workload
ESTIMATED_WORKLOAD_MEAN = 25
ESTIMATED_WORKLOAD_STD = 8.0


# Generate actual workload from estimated workload
ACTUAL_WORKLOAD_NOISE_STD = 5.0


# Reward
CORRECTLY_SELECTED_MIN_WORKLOAD_SERVER = 1
INCORRECTLY_SELECTED_MIN_WORKLOAD_SERVER = -1.5
SELECTED_NOT_ENOUGH_SERVER_CAPACITY = -1.5
DEFERRAL_WHILE_SPARE_SERVER_EXISTS = -1.5
CORRECTLY_DEFERRAL = 1
JOB_DONE = 4